apiVersion: v1
kind: Service
metadata:
  name: ftps-service
  labels:
    app: ftps
spec:
  type: LoadBalancer
  ports:
  - port: 21
    targetPort: 21
    protocol: TCP
    name: ftps
  - port: 20
    targetPort: 20
    protocol: TCP
    name: ftps-data
  - port: 20020
    targetPort: 20020
    protocol: TCP
    name: ftps-pass-min
  - port: 20021
    targetPort: 20021
    protocol: TCP
    name: ftps-pass-max
  externalIPs:
  - 192.168.99.242
  selector:
    app: ftps

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
  labels:
    app: ftps
spec:
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: ftps
        imagePullPolicy: Never
        ports:
        - containerPort: 21
          name: ftps-port
        - containerPort: 20
          name: ftps-data
        - containerPort: 20020
          name: ftps-pass-min
        - containerPort: 20021
          name: ftps-pass-max
      restartPolicy: Always
