apiVersion: v1
kind: Service
metadata:
  name: ftp-service
  labels:
    app: ftp
spec:
  type: LoadBalancer
  ports:
  - port: 21
    targetPort: 21
    protocol: TCP
    name: ftp
  - port: 20
    targetPort: 20
    protocol: TCP
    name: ftp-data
  - port: 20020
    targetPort: 20020
    protocol: TCP
    name: ftp-pass-min
  - port: 20021
    targetPort: 20021
    protocol: TCP
    name: ftp-pass-max
  externalIPs:
  - 192.168.99.242
  selector:
    app: ftp

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftp
  labels:
    app: ftp
spec:
  selector:
    matchLabels:
      app: ftp
  template:
    metadata:
      labels:
        app: ftp
    spec:
      containers:
      - name: ftp
        image: ftp-image
        imagePullPolicy: Never
        ports:
        - containerPort: 21
          name: ftp-port
        - containerPort: 20
          name: ftp-data
        - containerPort: 20020
          name: ftp-pass-min
        - containerPort: 20021
          name: ftp-pass-max
      restartPolicy: Always
