apiVersion: v1
kind: Service
metadata:
  name: ftp-service
  labels:
    app: ftp
spec:
  type: NodePort
  ports:
  - port: 21
    targetPort: 21
    nodePort: 21
    protocol: TCP
    name: ftp
  selector:
    app: ftp

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftp
  labels:
    app: ftp
spec:
  selector:
    matchLabels:
      app: ftp
  template:
    metadata:
      labels:
        app: ftp
    spec:
      containers:
      - name: ftp
        image: ftp-image
        imagePullPolicy: Never
        ports:
        - containerPort: 21
          name: ftp-port
