apiVersion: v1
kind: Service
metadata:
  name: pma-service
  labels:
    app: pma
spec:
  type: LoadBalancer
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
    name: pma
  selector:
    app: pma

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: pma
  labels:
    app: pma
spec:
  selector:
    matchLabels:
      app: pma
  template:
    metadata:
      labels:
        app: pma
    spec:
      containers:
      - name: pma
        image: pma-image
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
          name: pma-port
